config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events, only: %i(index)

  root to: redirect('/events')
  get 'events/new'
  get 'events/one'
  post 'events/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end
  def one
    @event = Event.first
    render json: @event
  end
  def new
  end
  def create
    Event.delete_all
    @event = Event.new(ActiveSupport::JSON.decode(request.raw_post))
    @event.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>Events calendar</h1>

<%= link_to 'Create event', events_new_path %>

<%= image_tag 'events_calendar', width: '100%' %>

<div id="app">
  <table width="50px">
    <thead>
    <tr>
      <th v-for="(w, idx) in week" :key="idx">{{ w.day }} <br> <span>{{ w.date }}</span></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td v-for="(w, idx) in week" :key="idx" :id="'td_' + idx">
      </td>
    </tr>
    </tbody>
  </table>
</div>

<script>
const app = new Vue({
    el: '#app',
    data: {
        weekday: [
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday',
            'Sunday'
        ],
        week: [],
        event: {}
    },
    created () {
        this.setWeek()
        this.getEvent()
        window.addEventListener('resize', this.handleResize);
    },
    watch: {
        event () {
            this.setEvent()
        }
    },
    methods: {
        handleResize () {
            this.setEvent()
        },
        setWeek () {
            const currentDay = new Date();
            const theYear = currentDay.getFullYear();
            const theMonth = currentDay.getMonth();
            const theDate  = currentDay.getDate();
            const theDayOfWeek = currentDay.getDay();

            const thisWeek = []

            for(let i=0; i<7; i++) {
                let resultDay = new Date(theYear, theMonth, theDate + (i - theDayOfWeek));
                let yyyy = resultDay.getFullYear();
                let mm = Number(resultDay.getMonth()) + 1;
                let dd = resultDay.getDate();

                mm = String(mm).length === 1 ? '0' + mm : mm;
                dd = String(dd).length === 1 ? '0' + dd : dd;

                thisWeek[i] = {
                    'date' : moment( yyyy + '-' + mm + '-' + dd ).format('Do MMM'),
                    'day' : this.weekday[resultDay.getDay()]
                }

            }
            this.week = thisWeek
        },
        setEvent () {
            const td = 'td_' + new Date(this.event.startd).getDay()
            const element = document.getElementById(td)

            const block = document.createElement('div')
            block.setAttribute('id', 'event')
            const title = document.createTextNode(this.event.title)
            const body = document.createTextNode(this.event.body)
            const author = document.createTextNode(this.event.author)
            const linebreak = document.createElement('br');
            const linebreak2 = document.createElement('br')

            block.appendChild(title)
            block.appendChild(linebreak)
            block.appendChild(body)
            block.appendChild(linebreak2)
            block.appendChild(author)

            block.style.backgroundColor='orange'
            block.style.position = 'absolute'
            block.style.width = element.clientWidth * (new Date(this.event.endd).getDay() - new Date(this.event.startd).getDay() + 1) + 'px'
            block.style.height = '7%'

            element.appendChild(block)
        },
        getEvent () {
            const opts = {
                method: 'GET'
            }

            fetch('events/one', opts)
                .then(res => res.json())
                .then((body) => {
                    const event = {
                        'startd': body.startd,
                        'endd': body.endd,
                        'title': body.title,
                        'body': body.body,
                        'author': body.author
                    }
                    this.event = event
            })
        },
    }
})
</script>

app/views/events/new.html.erb
<div id="create">
  <h1>{{ hello }}</h1>
  <form>
    <input v-model="title" placeholder="title">
    <input v-model="body" placeholder="body">
    <input v-model="author" placeholder="author">
    start :
    <select v-model="startd">
      <option v-for="(w, idx) in week" :key="idx" :value="w.date">{{w.date}}</option>
    </select>
    end :
    <select v-model="endd">
      <option v-for="(w, idx) in endSelection" :key="idx" :value="w.date">{{w.date}}</option>
    </select>
  </form>
  <button @click="createEvent">Create</button>
</div>

<script>
const create = new Vue({
    el: '#create',
    data: {
        hello: 'Create Event',
        title: '',
        body: '',
        author: '',
        week: [],
        startd: '',
        endd : '',
        endSelection : []
    },
    created() {
      this.setWeek()
    },
    watch : {
        startd (val) {
            const idx = this.week.findIndex(value => {
                return value.date === val
            })
            this.endSelection = this.week.slice(idx)
        }
    },
    methods : {
        createEvent () {
            const model = {
                'title': this.title,
                'body': this.body,
                'author': this.author,
                'startd': this.startd,
                'endd' : this.endd
            }

            const xhr = new XMLHttpRequest()
            xhr.open('POST', 'create')
            xhr.setRequestHeader('Content-Type', 'application/json')
            xhr.send(JSON.stringify(model))
            location.href = '/'
        },
        setWeek () {
            const currentDay = new Date();
            const theYear = currentDay.getFullYear();
            const theMonth = currentDay.getMonth();
            const theDate  = currentDay.getDate();
            const theDayOfWeek = currentDay.getDay();

            const thisWeek = []

            for(let i=0; i<7; i++) {
                let resultDay = new Date(theYear, theMonth, theDate + (i - theDayOfWeek));
                let yyyy = resultDay.getFullYear();
                let mm = Number(resultDay.getMonth()) + 1;
                let dd = resultDay.getDate();

                mm = String(mm).length === 1 ? '0' + mm : mm;
                dd = String(dd).length === 1 ? '0' + dd : dd;

                thisWeek[i] = {
                    'date' : yyyy + '-' + mm + '-' + dd,
                    'day' : resultDay.getDay()
                }

            }
            this.week = thisWeek
        },
    }
})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventCalendar</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <%= csrf_meta_tags %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>